/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

import 'vue'

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
  }
}
